### ISSUE TITLE
cell value can not be null

### ISSUE THREAD

**Issue by xjfnet** [schoetbi/XPTable#20]
`
public class Person
{
    public int Id { get; set; }
    public string Name { get; set; }
}

var set = new List<Person>()
{
    new Person() { Id = 1; }
};

table.DataSource = set;
`
then catch System.NullReferenceException

but this works well

`
var set = new List<Person>()
{
    new Person() { Id = 1; Name = string.Empty ;}
};
table.DataSource = set;
`

**Comment by adarmus** [comment]
I have added a fix here: [https://github.com/schoetbi/XPTable/pull/34](url)

Adam
