### ISSUE TITLE
Cannot select rows/cells programatically

### ISSUE THREAD

**Issue by janseris** [schoetbi/XPTable#48]
Row or Cell have no methods or settable properties to allow rows/cells to be selected programatically.

**Comment by adarmus** [comment]
The selection can be set with methods on TableModel, e.g. 

- SelectCell(int row, int column)
- SelectCell(CellPos cellPos)
- SelectCells(int startRow, int startColumn, int endRow, int endColumn)
- SelectCells(CellPos start, CellPos end)
- AddCell(int row, int column)
- AddCell(CellPos cellPos)
- AddCells(int startRow, int startColumn, int endRow, int endColumn)
- AddCells(CellPos start, CellPos end)
- AddShiftSelectedCell(int row, int column)
- AddShiftSelectedCell(CellPos cellPos)

Regards, Adam

**Comment by adarmus** [comment]
See comment
