### ISSUE TITLE
Bug in Renderer.cs that breaks the Visual Studio designer

### ISSUE THREAD

**Issue by jeoffman** [schoetbi/XPTable#5]
Just a friendly note about your branch:
There is a bug on line 126 of  XPTable/Renderers/Renderer.cs - don't dispose the font that was created elsewhere (especially if that font is a system font!)

I have the change working over here:
https://github.com/jeoffman/XPTable
if you want to see it. And there are no resource leaks as long as the creator of the font is disposing them properly.

**Comment by schoetbi** [comment]
Hi, thanks for the hint. I really would like to merge your branch, but there are also other changes included (e.g. removing gitstatus) that I really like. I will try to remove those changes that are not curical to the bug and incooperate this then.

Thanks, again, 
Tobias

**Comment by schoetbi** [comment]
Hi,

I saw that you are maintaining a nuget package for XPTable. I really like
it. Also the other changes are mostly ok. So what do you think to make only
one Github project for XPTable where both of us are colaborators? I do not
mind if it is yours or my repository. The main advantage would be to have a
single point for all issues questions and creation of releases.

What do you think?

/Tobias (schoetbi)

2016-02-16 16:19 GMT+01:00 jeoffman notifications@github.com:
