### ISSUE TITLE
The XPTABLE Not support .net6 ?

### ISSUE THREAD

**Issue by basis100** [schoetbi/XPTable#51]
Dear schoetbi:

I use XPTABLE in .net6 WinForm project.
but  when i drag the TABLE in UI Windows, show the error .

Whether the XPTABLE Not support .net6 or .net8?

**Comment by basis100** [comment]
Dear schoetbi:

I saw that armin released a new version that supports Net6，Can you help us add it to NUGET?
https://github.com/armin-pfaeffle/XPTable.Net
Thank you very much.

![QQ截图20240420114903](https://github.com/schoetbi/XPTable/assets/26346549/112d1164-6e8e-4daf-a832-30473c2a11b1)

**Comment by schoetbi** [comment]
Hi, @basis100 yes I can look into it next week.

**Comment by schoetbi** [comment]
@basis100 as promised, in the branch [DotNetMigration](https://github.com/schoetbi/XPTable/tree/DotNetMigration) I updated the version to .Net 6.0. Could you please check if this works as expected?

**Comment by basis100** [comment]
Dear schoetbi:
My current time is 23:00. I have created a new winform project by .net6, but the latest version of XPTABEL in NUGET is 1.6.1.139 in 2019. I will come back tomorrow to see if there is a NUGET cache available?
![QQ截图20240422230257](https://github.com/schoetbi/XPTable/assets/26346549/b25e1def-9d55-4881-b095-2faf7d26dd12)

**Comment by basis100** [comment]
Dear schoetbi:

**Comment by basis100** [comment]
Dear schoetbi:

I didn't see the latest version of net6 in NUGET, What do I need to do?
Best regards.

![Dingtalk_20240424091111](https://github.com/schoetbi/XPTable/assets/26346549/26403f5a-7448-46e0-84ea-1dfb636b320d)

**Comment by basis100** [comment]
Dear schoetbi:
The armin-pfaeffle's version can work in net6 , Can you put it in NUGET ?
https://github.com/armin-pfaeffle/XPTable.Net

Or can you tell me what I can do?

Best Regards.

**Comment by schoetbi** [comment]
@basis100 I created a pr #52 to publish the multitarget nuget package on nuget.org. @jeoffman did this last time. I hope he has time to build and publish the new version.

But until then you can always build the version from source on your own and replace the package references by assembly references in your project. Of course this is only a temporary solution until there is a proper nuget package available.

**Comment by basis100** [comment]
Dear schoetbi:
How to "build the version from source on your own and replace the package references by assembly references in your project."?
Can you give me some hints ?

thanks a lot.

**Comment by jeoffman** [comment]
@basis100   you can "git clone" this repo and add the XPTable.csproj to any solution. Once the project is in your solution you would remove the "nuget reference" and add a "project reference" directly to the XPTable.csproj - and then everything should just work.

Note that the version 2.0 nuget is up on nuget.org so you could also just update to that too.

**Comment by basis100** [comment]
Thank you very much. It's ready to use in .net6  winform.
