### ISSUE TITLE
XPtable support multi-Forms ？

### ISSUE THREAD

**Issue by basis100** [schoetbi/XPTable#53]
I have a new project, it contained three forms: form1,form2,form3.

The form2,form3 used this codes displayed in form1:   childForm.Show();

When I put the XPTable in form2 or form3, The error words:

"Error CS0246 Type or namespace name "table1" not found".

so , XPtable support multi-Forms in .net6 version 2.0.1？

**Comment by schoetbi** [comment]
I added a sample project here that displays two tables. For me, it worked fine.
https://github.com/schoetbi/XPTable/tree/master/Samples/MulitTableForm
