### ISSUE TITLE
In Column Selector dialog the last entry is not visible

### ISSUE THREAD

**Issue by schoetbi** [schoetbi/XPTable#8]
The last entry is only accessible with arrow keys.

**Comment by schoetbi** [comment]
@jeoffman could you please review my changes?

**Comment by jeoffman** [comment]
The code looks good. Do you have a test app to exhibit the problem? Something to give the issue some exercise?

**Comment by schoetbi** [comment]
Hi,
Yes i can commit it tomorrow.

Thanks
Tobias
Am 13.06.2016 20:00 schrieb "jeoffman" notifications@github.com:

**Comment by schoetbi** [comment]
@jeoffman Should I merge the branch?

**Comment by jeoffman** [comment]
It looks great! Thanks for the improvement!
